const baseUrl = Cypress.env("apiUrl");

const routes = {
  post: "POST",
  put: "PUT",
  get: "GET",
  /*************** Admin SIDE URL ***************/

  post_company : `${baseUrl}v1/admin/company/`,
  post_layout: `${baseUrl}v1/admin/layouts/`,
  post_users : `${baseUrl}v1/admin/users/`,
  business_flow:`${baseUrl}v1/admin/settings/business-flow/`,
  post_role:`${baseUrl}v1/admin/roles/`,

  /*************** USER SIDE URL ***************/
  csv_import: `${baseUrl}v1/csv_upload_detail/import_csv`,
  check_queue_status: `${baseUrl}v1/csv_upload_detail/check_queue_status/`,
  csv_download: `${baseUrl}v1/csv_upload_detail/download_csv/`,
  csv_sample_download: `${baseUrl}v1/csv_upload_detail/download_sample/`,
  look_up: `${baseUrl}v1/modules/lookup/`,
  track_change: `${baseUrl}v1/log/track_change`,
  get_log: `${baseUrl}v1/log/getlog`,
  post_body: `${baseUrl}v1/body/`,
  post_category: `${baseUrl}v1/category/`,
  post_color : `${baseUrl}v1/color/`,
  post_csku : `${baseUrl}v1/csku/`,
  post_cst_add : `${baseUrl}v1/customer_address/`,
  post_cst_contact : `${baseUrl}v1/customer_contacts/`,
  post_cst_store: `${baseUrl}v1/customer_store/`,
  post_cstSales : `${baseUrl}v1/customer_salesperson/`,
  post_cst : `${baseUrl}v1/customers/`,
  post_dc : `${baseUrl}v1/customer_distribution_center/`,
  post_dept : `${baseUrl}v1/customer_department/`,
  post_design: `${baseUrl}v1/design/`,
  post_division:`${baseUrl}v1/division/`,
  post_division_address: `${baseUrl}v1/division_address/`,
  post_division_conatct: `${baseUrl}v1/division_contact/`,
  post_factor : `${baseUrl}v1/factor/`,
  post_factor_address: `${baseUrl}v1/factor_address/`,
  post_group: `${baseUrl}v1/group/`,
  post_item: `${baseUrl}v1/item/`,
  post_PO: `${baseUrl}v1/import_po/`,
  post_queue :`${baseUrl}v1/queue/`,
  post_retail: `${baseUrl}v1/retail_type/`,
  post_roleModule: `${baseUrl}v1/role-module/`,
  post_royalty: `${baseUrl}v1/royalty/`,
  post_season: `${baseUrl}v1/season/`,
  post_size: `${baseUrl}v1/sizes/`,
  post_shipment: `${baseUrl}v1/import_shipment/`,
  post_SO: `${baseUrl}v1/sales_order/`,
  post_SP: `${baseUrl}v1/sales_person/`,
  post_SP_address: `${baseUrl}v1/sales_person_addresses/`,
  post_SP_contact: `${baseUrl}v1/sales_person_contact/`,
  post_SV: `${baseUrl}v1/ship_via/`,
  post_SV_adress: `${baseUrl}v1/ship_via_addresses/`,
  post_SV_contact: `${baseUrl}v1/ship_via_contact/`,
  post_stage: `${baseUrl}v1/stage/`,
  post_template: `${baseUrl}v1/template/`,
  post_terms: `${baseUrl}v1/terms/`,
  post_user : `${baseUrl}v1/users/`,
  put_user : `${baseUrl}v1/users`,
  post_vendor_address: `${baseUrl}v1/vendor_address/`,
  post_vendor_contact: `${baseUrl}v1/vendor_contact/`,
  post_warehouse : `${baseUrl}v1/warehouse/`,
  post_warehouse_address: `${baseUrl}v1/warehouse_address/`,
  post_warehouse_conatct: `${baseUrl}v1/warehouse_contact/`,
  fetch_color: `${baseUrl}v1/color/fetch`,
  csv_fetch: `${baseUrl}v1/csv_upload_detail/fetch`,
  csv_fetch_error: `${baseUrl}v1/csv_upload_detail/fetch_errors/`,
  fetch_cst: `${baseUrl}v1/customers/fetch`,
  fetch_cst_dept: `${baseUrl}v1/customer_department/fetch`,
  fetch_factor_address: `${baseUrl}v1/factor_address/fetch`,
  fetch_design: `${baseUrl}v1/design/fetch`,
  fetch_division: `${baseUrl}v1/division/fetch`,
  fetch_PO: `${baseUrl}v1/import_po/fetch`,
  fetch_item: `${baseUrl}v1/item/fetch`,
  fetch_module: `${baseUrl}v1/modules/fetch`,
  fetch_org: `${baseUrl}v1/organization/fetch`,
  fetch_retail: `${baseUrl}v1/retail_type/fetch`,
  fetch_role: `${baseUrl}v1/roles/fetch`,
  fetch_royalty: `${baseUrl}v1/royalty/fetch`,
  fetch_factor: `${baseUrl}v1/factor/fetch`,
  fetch_sales_person: `${baseUrl}v1/sales_person/fetch`,
  fetch_ship_via: `${baseUrl}v1/ship_via/fetch`,
  fetch_shipment: `${baseUrl}v1/import_shipment/fetch`,
  fetch_SO: `${baseUrl}v1/sales_order/fetch`,
  fetch_SP: `${baseUrl}v1/sales_person/fetch`,
  fetch_SP_address: `${baseUrl}v1/sales_person_addresses/fetch`,
  fetch_statge: `${baseUrl}v1/stage/fetch`,
  fetch_terms: `${baseUrl}v1/terms/fetch`,
  fetch_vendor: `${baseUrl}v1/vendor/fetch`,
  fetch_vendor_address: `${baseUrl}v1/vendor_address/fetch`,
  fetch_vendor_contact: `${baseUrl}v1/vendor_contact/fetch`,
  fetch_warehouse: `${baseUrl}v1/warehouse/fetch`,
  fetch_warehouse_address: `${baseUrl}v1/warehouse_address/fetch`,
  fetch_warehouse_contact: `${baseUrl}v1/warehouse_contact/fetch`,
};

export default routes;
