const store_msg = {
  success_post: `Success test case for create api of `,
  success_put: `Success test case for update api of `,
  success_fetch: `Success test case for fetch api of `,
  success_get: `Success test case for get api of `,
  success_log: `Success test cases for Log and Look-up of `,
  fail_post: `Failure test case for create api of `,
  fail_put: `Failure test case for update api of `,
  fail_fetch: `Failure test case for fetch api of `,
  layout_msg: `Following file(s) are available for this {type}`,
  allField_msg: `Create  with all field`,
  fail_get: `Failure test case for get api of `,
  fail :`Failure test cases of `,
  success :`Success test cases of `,
  delete : `Test cases for delete via update of `,
  id:`{id} is invalid`,
  item_grid :`{item_grid_id} is not associated with {item_id}`,
  division:`{division_id} is invalid`,
  item:`{item_id} is invalid`,
  chk_id :`{id} must be a number`,
  err_code :`{code} with value "" fails to match the required pattern: /^[a-zA-Z0-9_-]{1,40}$/`,
  err_code1: `{code} must be a string`,
  err_code2: `{code} already exists`,
  err_code3: `{code} is required`,
  err_name:`{name} is not allowed to be empty`,
  err_name1:`{name} must be a string`,
  err_name2: `{name} is required`,
  err_status :`{status} must be one of [1, 0]`,
  err_status1 :`{status} must be a number`,
  err_contact_name : `{contact_name} is required`,
  err_type: `{type} is required`,
  err_address1:`{address_1} is required`,
  err_city :`{city} is required`,
  err_state:`{state} is required`,
  err_zip:`{zip} is required`,
  err_country:`{country} is required`,
  empty_contact_name : `{contact_name} is not allowed to be empty`,
  empty_type: `{type} is not allowed to be empty`,
  empty_address1:`{address_1} is not allowed to be empty`,
  empty_city :`{city} is not allowed to be empty`,
  empty_state:`{state} is not allowed to be empty`,
  empty_zip:`{zip} is not allowed to be empty`,
  empty_country:`{country} is not allowed to be empty`,
  string_contact_name : `{contact_name} must be a string`,
  string_type: `{type} must be a string`,
  string_address1:`{address_1} must be a string`,
  string_address2:`{address_2} must be a string`,
  string_address3:`{address_3} must be a string`,
  string_address4:`{address_4} must be a string`,
  string_city :`{city} must be a string`,
  string_state:`{state} must be a string`,
  string_zip:`{zip} must be a string`,
  string_country:`{country} must be a string`,
  chk_factor : `{factor_id} must be a number`,
  err_disc : `{description} must be a string`,
  invalid_org: `{org_id} is not valid`,
  invalid_company : `{company_id} is invalid`
};

export default store_msg;
